openapi: 3.0.3
info:
  title: Django DRF Ecommerce
  version: 0.0.0
paths:
  /product-by-id/{id}:
    get:
      operationId: product_by_id_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - product-by-id
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: product_by_id_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - product-by-id
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: product_by_id_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - product-by-id
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /product-list/:
    get:
      operationId: product_list_retrieve
      tags:
      - product-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: product_list_create
      tags:
      - product-list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
